### ISSUE TITLE
Number of blue agents.

### ISSUE THREAD

**Issue by davidADSP** [cage-challenge/cage-challenge-4#1]
Is there a reason for there being 18 Dummy Agents on the sample submission page?

https://codalab.lisn.upsaclay.fr/competitions/17672#participate

In the docs, there are only 5 blue agents.

Thanks!

**Comment by cage-challenge** [comment]
Hi @davidADSP,

Apologies, that was a remnant left over from the CAGE challenge 3. There are only 5 blue agents in this challenge.

**Comment by rykrr** [comment]
Same issue applies to homepage. Will fix.
