### ISSUE TITLE
documentation: tensorboard call with missing logs folder

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#14]
there's a call to tensorboard --logdir logs/ 

in in https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/3_Training_Agents.md 

At this point, there are no logs files?

**Comment by rykrr** [comment]
Tensorboard can be set to automatically refresh and display new results as the log directory is populated.

**Comment by rykrr** [comment]
My apologies, I just noticed that the training example in the documentation was not synced with the training example script provided. The full training script at `CybORG/Evaluation/training_examples/TrainingRay.py` was set up to log everything, while the documentation version was missing that line. I have added this missing line and have added a reference to the full training script to the top of the page.
