### ISSUE TITLE
host_state_priority_list instruction confusing

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#16]
the line "new_host_state_priority_list = {'K':(0->100), 'KS':?, 'KD':?, 'U':?, 'UD':?, 'R':?, 'RD':?}"  is confusing in https://cage-challenge.github.io/cage-challenge-4/pages/reference/agents/red_overview/    

Needs more explanation: looking at the code, I assume that the list of values should sum to 100?

**Comment by onaish-dstl** [comment]
Yes it should sum to 100. There is a bit of info about it in the docs [here](https://cage-challenge.github.io/cage-challenge-4/pages/reference/agents/red_overview/#host-priority).

As it is not part of the cage challenge, just a nifty feature of the FSM red agent for future research/analysis, I haven't really written much up on it. The agent that the challenge will be tested on is the FiniteStateRedAgent given.
