### ISSUE TITLE
documentation: finding print_output

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#17]
really low priority: I hate modifying code, so when I saw the print_output instructions in https://cage-challenge.github.io/cage-challenge-4/pages/tutorials/02_Looking_Around/2_Agents/ I went looking for the variable to set.  Is this the cleanest way to do that? 

cyborg.environment_controller.agent_interfaces['red_agent_0'].agent.print_output = True

**Comment by onaish-dstl** [comment]
Pretty much, yes.
As it is a debugging/furthering code understanding feature unique to the FSM red agents, the ability to increase verbosity is not natively supported through the environment.

You can either set it in your code (through the cyborg instance) or just set it in the agent code to True.

Hope that helps @bodacea :relaxed:
