### ISSUE TITLE
Challenge 4 BlueEnterpriseWrapper - BlockTrafficZone and AllowTrafficZone don't produce the expected result

### ISSUE THREAD

**Issue by William-John-Valentine** [cage-challenge/cage-challenge-4#18]
After an agent uses the BlockTrafficZone action, I would expect to see a change in the "Blocked Subnets" section(s) of the observation vector. I see no changes.

```action.get_params()``` shows that BlockTrafficZone causes an error to be logged, for example:

![image](https://github.com/cage-challenge/cage-challenge-4/assets/152826510/369e43a4-45db-4f5d-86f1-387907482748)

In CybORG/Simulator/Actions/ConcreteActions/ControlTraffic.py, the ```execute_control_traffic()``` methods of ```BlockTrafficZone``` and ```AllowTrafficZone``` both search ```state.subnet_name_to_cidr.keys()``` (the subnet names) to determine if a subnet is valid, however BlueFixedActionWrapper's ```_populate_action_space()``` passes the CIDR values for the ```from_subnet``` and ```to_subnet``` parameters (line 278 of BlueFixedActionWrapper.py).

**Comment by rykrr** [comment]
Hi @William-John-Valentine,

 Thank you very much for the detailed bug report! I have put together a quick fix and updated the tests in `rk-fix-wrapper-zonectrl`. These changes appear to be compatible with how actions handle blocking, however, I haven't had the chance to fully verify this and I will try my hand at putting together a more comprehensive test once I have a bit more time to spare. In the meantime, would you be willing to verify that this works?

Thank you again,
- R

**Comment by rykrr** [comment]
Thank you for checking, much appreciated!
