### ISSUE TITLE
Challenge 4 BlueEnterpriseWrapper, incorrect communication policy vectors in observations

### ISSUE THREAD

**Issue by William-John-Valentine** [cage-challenge/cage-challenge-4#19]
[Appendix B - Agent observation](https://github.com/cage-challenge/cage-challenge-4?tab=readme-ov-file#appendix-b--agent-observation) of the README states that agent observation vectors contain the communication policy for each subnet. A value of ```1``` indicates a subnet should be blocked, ```0``` indicates a subnet should not be blocked.

This communication policy vector instead seems to contain a vector where a ```1``` indicates an intended *unblocked* connection with only *adjacent* subnets, and a ```0``` either indicates that the subnet should be blocked *or* that the subnet is simply not adjacent.

For example, in phase 1, Restricted Zone A's communications policy observation is ```[0 0 1 0 1 0 0 0 0]``` where indices 2 and 4 represent the Internet and Operational Zone A subnets respectively.
The [network diagram](https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/assets/CAGE-Network-Diagram.png) shows that these are the two subnets adjacent to Restricted Zone A, and the [phase 1 communication policy table](https://github.com/cage-challenge/cage-challenge-4?tab=readme-ov-file#table-1-initial-network-communication-security-policy-----mission-pre-planning-phase) states that the two subnets indeed ought to be unblocked by Restricted Zone A, however the communication policy table states that Restricted Zone A should also have unblocked HQ (all of its subnets or just the public access subnet?), Contractor Network, and Restricted Zone B

So I believe Restricted Zone A's communications policy observation in phase 1 should be something like ```[0 0 0 0 0 1 0 0 0]``` where index 5 represents Operational Zone B.

**Comment by rykrr** [comment]
Issue appears to stem from `BlueFlatWrapper::_build_comms_policy_network` (line 266) inherited without any changes from the original `BlueWrapper`. This function seems to create a graph of network adjacencies rather than connectivity/policy as you have pointed out. I will change this to reflect the policy and possibly try to figure out why it was written this way to begin with.
