### ISSUE TITLE
link in readme fails

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#2]
clicking on [the Installation Instruction guide](https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/00_Introduction) from the readme goes to a hole

**Comment by onaish-dstl** [comment]
Hi. Thanks for the heads up! I will get that changed.

The link should be to : https://cage-challenge.github.io/cage-challenge-4/pages/tutorials/01_Getting_Started/1_Introduction/

**Comment by onaish-dstl** [comment]
Changes made to docs-changes branch. Will be added to docs on completion of other documentation issues
