### ISSUE TITLE
RandomAgent action space gym import

### ISSUE THREAD

**Issue by rliu100** [cage-challenge/cage-challenge-4#25]
Should the [import](https://github.com/cage-challenge/cage-challenge-4/blob/main/CybORG/Agents/SimpleAgents/RandomAgent.py#L4) at the beginning of RandomAgent be `from gymnasium import Space`?

Below, I've used `RandomAgent` in my submission.py file, similar to the example with `DummyAgent`.

```
class Submission:

    # Submission name
    NAME: str = "SUBMISSION NAME"

    # Name of your team
    TEAM: str = "TEAM NAME"

    # What is the name of the technique used? (e.g. Masked PPO)
    TECHNIQUE: str = "TECHNIQUE NAME"

    # Use this function to define your agents.
    AGENTS: dict[str, BaseAgent] = {
        f"blue_agent_{agent}": RandomAgent() for agent in range(5)
    }

    # Use this function to wrap CybORG with your custom wrapper(s).
    def wrap(env: CybORG) -> MultiAgentEnv:
        return EnterpriseMAE(env)
```

However, if I run the evaluation.py script, I get the following message because the action space is of type `gymnasium.spaces.Discrete`.
```
ValueError: Random agent can only handle Space or dict action space
```
If I change the import to `from gymnasium import Space`, the error goes away.

**Comment by onaish-dstl** [comment]
@MitchellKiely - Is this an issue on your end?

**Comment by MitchellKiely** [comment]
Apologies @rliu100 for the late reply, I just returned from leave. Yes, you are correct, this was a remnant from the previous CAGE challenges. Thanks for picking up on this mistake, I've pushed the changes to main.
