### ISSUE TITLE
tkinter install will fail for mac? 

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#3]
not a biggie. In install instructions, https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/1_Introduction.md,  "sudo apt install python3-tk --assume-yes" has issues (the usual 'install more java' message) on a mac

**Comment by rykrr** [comment]
Hi there! The documentation was created for Ubuntu. Mac OS is not technically supported by our team, however, tkinter can be installed using the [homebrew](https://brew.sh/) package manager with the command `brew install tkinter`.
