### ISSUE TITLE
Does "Restore" remove decoys?

### ISSUE THREAD

**Issue by kasanari** [cage-challenge/cage-challenge-4#33]
Since Restore is supposed to emulate re-imaging a host, does it remove previously deployed decoys?

**Comment by MitchellKiely** [comment]
That's a very good question @kasanari. It took me a while to chase down the answer, but I can confirm that the Restore action does indeed remove previously deployed decoys on a given host. 

The decoy action adds a process onto a host/server, and these processes can be checked. For example, the processes actively running on 'restructed_zone_a_subnet_server_host_0 can be found at `cyborg.environment_controller.state.hosts['restricted_zone_a_subnet_server_host_0'].processes`. After deploying a decoy on this machine, the process associated with the decoy is appended to this list. After restoring the machine, the process is removed and only the original processes remain, thus the decoy was removed.
