### ISSUE TITLE
Support for torch_geometric in submissions? 

### ISSUE THREAD

**Issue by zazyzaya** [cage-challenge/cage-challenge-4#37]
Our team is taking a Graph-theoretic approach to the problem, and to do this we were using PyTorch Geometric (v. 2.5.0). It doesn't appear that this module is available in the codalabs environment, as we're getting this error in the ingestion error log:

`Traceback (most recent call last):
  File "/tmp/codalab/tmpBE9u0e/run/ingestion_program/ingestion.py", line 38, in <module>
    submission = load_agent(submission_program)
  File "/tmp/codalab/tmpBE9u0e/run/ingestion_program/ingestion.py", line 21, in load_agent
    spec.loader.exec_module(agent_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/codalab/tmpBE9u0e/run/program/submission.py", line 10, in <module>
    from cage4 import load_inductive_ppo
  File "/tmp/codalab/tmpBE9u0e/run/program/cage4.py", line 5, in <module>
    from torch_geometric.nn import GCNConv
ModuleNotFoundError: No module named 'torch_geometric'
`

Would it be possible to add this module in, or should we find a workaround?

**Comment by MitchellKiely** [comment]
Hi @zazyzaya,

I've added in torch_geometric v.2.5.0 into the Requirements.txt file in commit 313bf33. Thankfully, all dependencies were already met, so no other libraries were impacted. You should be able to submit your agent to Codalabs within the hour.

**Comment by zazyzaya** [comment]
Hello @MitchellKiely . Thank you for your response. Unfortunately, we resubmitted just now, and we get the same error message

**Comment by MitchellKiely** [comment]
Hi @zazyzaya, can you confirm whether you reuploaded everything from scratch or did you click the rerun icon on Codalabs?

**Comment by zazyzaya** [comment]
Yes, we reuploaded everything from scratch. If you have visibility into our submission files (my username is iking on codalabs), they are submissions 5-7. We found a workaround though by just uploading a few of the torch geo source files with our submission, so feel free to close the issue unless others need the module

**Comment by cage-challenge** [comment]
Awesome! Glad that the submission was able to go through. I'll leave
torch_geometric in the requirements just because it'll be more hassle to
remove. Looks like your approach is very promising.

I'll close the issue.
