### ISSUE TITLE
Evaluation.py does not call end_episode for agents

### ISSUE THREAD

**Issue by dvanbrug** [cage-challenge/cage-challenge-4#39]
In recent testing of an agent for submission, I noticed that Agents that are submitted as part of the submission package are not reset in between episodes.

I had expected agents would have their `end_episode()` method called, similar to how agents are reset within the `simulation_controller` when reset is called. 

As a work around, if state needs to be reset between episodes, I think we can keep track of the number of steps taken within the agent and reset logic pieces (and step counts) if the step count ever gets to the max value. I think the current max value is 499 steps.

**Comment by cage-challenge** [comment]
Hi @dvanbrug,
The agents themselves shouldn't be required to reset via the `end_episode()` function at the end of each episode. The environment is required to be reset (as it varies with each episode), which is executed on line 90 of evaluation.py with the command `wrapped_cyborg.reset()`. This gives each agent the new action_space, observation_space, done values, etc... The `end_episode()` function is a remnant from older versions of CybORG which is on the chopping block of list of things to remove in future additions.

**Comment by dvanbrug** [comment]
Hi @cage-challenge, it is my understanding that the `AGENTS` that are part of the submission package are independent from the `wrapped_cyborg` environment. Therefore, I do not see how they would have their state reset during a `wrapped_cyborg.reset()` call.

At least that was my interpretation with the AGENTS being setup once as part of the example submission:
https://github.com/cage-challenge/cage-challenge-4/blob/313bf330e5229663606de08df0d0d5135b55961d/CybORG/Evaluation/example_submission/submission.py#L23-L25

I can see how any opponent agents (e.g. RedFiniteStateAgent) would be reset, but not the submitted agents.  I had been exploring using agents that kept additional state to augment their policies which would need to be reset in between each episode and that's where I running into this issue.

**Comment by cage-challenge** [comment]
Ah, I see what you mean now @dvanbrug . Yes, if you are keeping track of additional states within your agent then your agent itself must have a methodology which resets itself during each episode. As you stated, if your agent is internally keeping track of a step count then it should be possible to reset every 499 steps within your agent's codebase.
