### ISSUE TITLE
wrong test file name in install instructions? 

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#4]
install instructions, In install instructions, https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/1_Introduction.md, suggest "pytest ./CybORG/Tests/test_sim" - the only test file in that directory is test_cc4

**Comment by onaish-dstl** [comment]
Changes made to docs-changes branch. Will be added to docs on completion of other documentation issues
