### ISSUE TITLE
example markdown has "???+ Quote "Code Output""

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#6]
Markdown in examples has "???+ Quote "Code Output"" before each code output, e.g. in https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/2_Getting_Started.md.  I'm assuming this is a piece of markdown gone a bit awry?

**Comment by rykrr** [comment]
Hi! This syntax is used by mkdocs to create call-outs and collapsable cells on the webpage. You can see this in action [here](https://cage-challenge.github.io/cage-challenge-4/pages/tutorials/01_Getting_Started/2_Getting_Started/).
