### ISSUE TITLE
Link to AppendixB is broken in 2_getting_started

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#8]
Link to appendix b "Note For a full breakdown of how the observation vectors are structured, see [Appendix B](https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/index.md#appendix-b-agent-observation)." is broken in https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/2_Getting_Started.md

**Comment by onaish-dstl** [comment]
Changes made to docs-changes branch. Will be added to docs on completion of other documentation issues
